## Numpy :-
   - Numerical Python
   - can create multidimensional array and perform operation on that

### Array:-
   - Datatype in python
   - container datatype which can store multiple values
   - support indexing
   - mutable >> change values
   - homogenous >> same data type
   - array is faster than list
   - numpy lib >> c, python
   - 1D array >> list >> vector >> column >> series
   - 2D array >> list in list >> table >> matrix >> dataframe
   - 3D array >> list in list in list >> panel

In [1]:
import numpy as np

In [8]:
# 1 D array
arr=np.array([11,22,33,44])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[11 22 33 44]
(4,)
1
int64
4


In [10]:
# indexing
arr[0]

np.int64(11)

In [11]:
arr[2]

np.int64(33)

In [12]:
# slicing
arr[0:3]

array([11, 22, 33])

In [13]:
# boolean slicing
arr[arr>30]

array([33, 44])

In [27]:
arr[(arr>20) & (arr<40)] # and

array([22, 33])

In [29]:
arr[(arr>20) | (arr<40)] # or

array([11, 22, 33, 44])

In [30]:
# mutable
arr=np.array([11,22,33,44])

In [31]:
arr[0]=99

In [32]:
arr

array([99, 22, 33, 44])

In [33]:
# reshape
a=np.array([1,2,3,4,5,6])

In [34]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
# arange
x=np.arange(1,11,2)

In [42]:
x

array([1, 3, 5, 7, 9])

In [47]:
x=np.arange(1,101).reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [48]:
# 2D array

In [50]:
a=np.array([[1,2,3],[4,5,6]]) # inner list represent row
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a.shape

(2, 3)

In [52]:
#4,3
a2=np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
a2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [54]:
# indexing & slicing on 2D array
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [55]:
a.ndim

2

In [56]:
a[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
a[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
a[[0]] # for answer in 2D array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [61]:
#slicing
# a[row_slicing, column_slicing]
a[0:5, 0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [62]:
a[:, 0:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [68]:
a[:,[-1]]

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [69]:
# row 0, 3 & col 1,9
a[[0,3],[1,9]]

array([ 2, 40])

In [70]:
a[[0,3],:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [71]:
# boolean slicing 
a[a>40]

array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [73]:
# arithmatic operations
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [74]:
a+b

array([ 7,  9, 11, 13, 15])

In [75]:
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [76]:
a-b

array([-5, -5, -5, -5, -5])

In [77]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [78]:
a*b

array([ 6, 14, 24, 36, 50])

In [79]:
a=np.array([1,2,3,4])
b=np.array([[11,22,33,44],[66,77,88,99]])

In [81]:
# broadcasting - lower dimensional array convert into high dimension array
a+b

array([[ 12,  24,  36,  48],
       [ 67,  79,  91, 103]])

In [82]:
b+2

array([[ 13,  24,  35,  46],
       [ 68,  79,  90, 101]])

In [83]:
# stats operation

In [85]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
a.sum()

np.int64(136)

In [88]:
a.min(), a.max()

(np.int64(1), np.int64(16))

In [89]:
a.argmax() # index of max value

np.int64(15)

In [90]:
a.argmin()

np.int64(0)

In [91]:
a.mean()

np.float64(8.5)

In [92]:
a.var() # spreadness of data from mean

np.float64(21.25)

In [94]:
a.std()

np.float64(4.6097722286464435)

In [95]:
np.median(a)

np.float64(8.5)

In [98]:
np.quantile(a,0.75), np.quantile(a,0.50)

(np.float64(12.25), np.float64(8.5))

In [99]:
np.quantile(a,0.25)

np.float64(4.75)

In [101]:
a.size

16

### 3D Array
   - list in list in list

In [3]:
a=np.array([[[1,2,3]]])
a

array([[[1, 2, 3]]])

In [4]:
a.ndim

3

In [5]:
a.shape

(1, 1, 3)

In [14]:
#3,2,3
p=np.array([
    [[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2]],
    [[3,3,3],[3,3,3]]
])
p.shape

(3, 2, 3)

In [15]:
#concate method

In [16]:
a=np.arange(1,17).reshape(4,4)
b=np.arange(17,33).reshape(4,4)

In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [19]:
a+b

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [20]:
np.concatenate((a,b), axis=0) # 0 >> rows & 1 >> column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [21]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [27]:
np.hstack((a,b)) # column wise concatenation

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [28]:
np.vstack((a,b)) # row wise concatenation

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [33]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [34]:
np.split(a,2)[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
a[0]

array([1, 2, 3, 4])

In [37]:
b=np.arange(17,33).reshape(4,4)

In [38]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [40]:
np.where(b<30, b, b*10)

array([[ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29, 300, 310, 320]])

In [43]:
# even - 1, odd - 0
np.where(b%2==0, 1, 0)

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])